- become: true
  gather_facts: false
  handlers:
  - ansible.builtin.package:
      name: socat
      state: absent
    name: Uninstall testing requirements
  hosts: all
  name: Verify
  tasks:
  - ansible.builtin.package:
      name: socat
      state: present
    name: Install testing requirements
    notify:
    - Uninstall testing requirements
  - ansible.builtin.wait_for:
      port: '{{ item }}'
    loop:
    - 80
    - 443
    name: Check if port responds
  - ansible.builtin.uri:
      status_code:
      - 200
      url: '{{ item }}'
      validate_certs: false
    loop:
    - http://localhost/
    - https://localhost/
    name: Check of content can be retrieved
  - ansible.builtin.shell: 'set -euo pipefail

      echo ''show stat'' | socat unix-connect:/var/lib/haproxy/stats stdio

      '
    changed_when: false
    name: Check if stats are available
