---
- become: true
  gather_facts: false
  handlers:
    - ansible.builtin.package:
        name: socat
        state: absent
      name: Uninstall testing requirements
  hosts: all
  name: Verify
  tasks:
    - ansible.builtin.package:
        name: socat
        state: present
      name: Install testing requirements
      notify:
        - Uninstall testing requirements
    - ansible.builtin.file:
        path: /tmp/haproxy_test_backend
        state: directory
        mode: "0755"
      name: Create test backend content directory
    - ansible.builtin.copy:
        content: "Hello World!"
        dest: /tmp/haproxy_test_backend/index.html
        mode: "0644"
      name: Place sample index.html for the backend haproxy proxies to
    - ansible.builtin.command: >-
        systemd-run --unit=haproxy-test-backend
        --working-directory=/tmp/haproxy_test_backend
        python3 -m http.server 8080
      name: Start a test backend web server on port 8080
      changed_when: true
    - ansible.builtin.wait_for:
        port: "{{ item }}"
      loop:
        - 80
        - 443
      name: Check if port responds
    - ansible.builtin.uri:
        status_code:
          - 200
        url: "{{ item }}"
        validate_certs: false
      loop:
        - http://localhost/
        - https://localhost/
      name: Check of content can be retrieved
      register: _haproxy_content_check
      until: _haproxy_content_check.status == 200
      retries: 5
      delay: 2
    - ansible.builtin.shell: "set -euo pipefail

        echo 'show stat' | socat unix-connect:/var/lib/haproxy/stats stdio

        "
      args:
        executable: /bin/bash
      changed_when: false
      name: Check if stats are available
